name: deploy to lambda
on: [push]
jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./backend
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: IQoJb3JpZ2luX2VjEG4aCXVzLXdlc3QtMiJHMEUCIFjIqF0eUs48iNvN+4r4JBV5CwS1+btJ53zRztcpGVliAiEA8olN8LwsRwiU7hJkaYgPxXRINScKcdDSVpU1m74UtKwqtwIIFxAAGgw3MTQ1NDQ3MjM1MjAiDJ/kmB5qzxmw3V+aWyqUAuR/RSUBZr29zTvma9gTlWA+PIUIssTiCuxa3QeE8wVEu4PI/EI7bBKdujQbFmCuMOiuVnQ2GLmSbFcDOovlW0J5cV7QYK5tuoQhKaZbpV+4Q7Z3YK8ez9FxmH5HbabOPv8Gjw7EWRO0aLMR/J9yMzQ4M6DnmGD069v8aJit5LuTvkbI+COZR+PZblsq1l5SsJVZRS025NZYkDHiV9DvpT/N+5EjWPwAk4/Fj9RQkG7fR2ayf2qcGJuooZ7Cf0pi8B4TIphTDxX7hToS8ekAuxf25X9DVAqgTHuzY855l2jlUbFfQYM09YpbtUAyoOt/7uqOWoi2jXW4eyhb93jKtGjCVuD3ittj2rLCCiXATeV/nHwmyTDU9rOFBjqdAQpKBXWwZ5jHVL62RV2euwnYeExfPeibiTXqipTgPwAZEJTMJ1w0ugnfGCSYxiGqkG4IaqcTroHo80mreYWnVHnArUQYmsc5IfPsGAiqbzgD2ypgNW8Dp1I2PF3jjb39e5L8+H/+azwveUP+ANHbj63vgaa7Hbx7ZTDY4OUpdGrW1CnzBDoZNYFNrTcrktMWIt80H6pbUszPxEcEQu8=
          aws_region: eu-west-1
          function_name: sam-app-HelloWorldFunction-vduenSz5yJ2N
          zip_file: bundle.zip
